# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
version: 2.1

orbs:
  python: circleci/python@2.1.1
  platform-helpers-general: okta/general-platform-helpers@1.8
  platform-helpers: okta/platform-helpers@1
  aws-cli: circleci/aws-cli@5.1

jobs:

  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: pip wheel -r requirements.txt -w _vendor/

      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:

  "Malware Scanner":
    jobs:
      - platform-helpers/job-reversinglabs-scan:
          context:
            - static-analysis
          requires:
            - build
